### PR TITLE
Sh

### PR DESCRIPTION
**Pull request by mhurtado2**
I added some html with the monsters name, species, and hobbies

### CODE REVIEW

**Review by thegoodcorg — APPROVED** [review]
es bonita

**Review by NelsonTaylorLumpkin — APPROVED** [review]
OHHH SOOOOO GURDDDD

**Review by bigjlr2004 — APPROVED** [review]
LOOKING GOOD.

**Comment by mhurtado2** [comment]
thank you for checking it out!

**Pull request merged**
