### PR TITLE
css and header/footer

### PR DESCRIPTION
**Pull request by thegoodcorg**
see above email.

### CODE REVIEW

**Review by mhurtado2 — APPROVED** [review]
Hell ya brother

**Review by NelsonTaylorLumpkin — APPROVED** [review]
I kind of love this a little bit!

**Review by bigjlr2004 — CHANGES_REQUESTED** [review]
no go need more info

**Comment by thegoodcorg** [comment]
Updated file with the header information this time @bigjlr2004

**Review by bigjlr2004 — APPROVED** [review]
Looks a-lot better

**Pull request merged**
